const colors = {
  light: {
    text: "#0D1B3E",
    tint: "#1B3A7A",
    background: "#F4F6FA",
    foreground: "#0D1B3E",
    card: "#FFFFFF",
    cardForeground: "#0D1B3E",
    primary: "#1B3A7A",
    primaryForeground: "#FFFFFF",
    secondary: "#EAF0FB",
    secondaryForeground: "#1B3A7A",
    muted: "#E4EAF5",
    mutedForeground: "#6B7A99",
    accent: "#2563EB",
    accentForeground: "#FFFFFF",
    destructive: "#DC2626",
    destructiveForeground: "#FFFFFF",
    border: "#D0D9EC",
    input: "#E8EDF8",
    success: "#16A34A",
    successForeground: "#FFFFFF",
    warning: "#D97706",
    warningForeground: "#FFFFFF",
    silver: "#8094B4",
    surface: "#FFFFFF",
  },
  dark: {
    text: "#E8ECF4",
    tint: "#4B7BF5",
    background: "#050B1A",
    foreground: "#E8ECF4",
    card: "#0D1E3D",
    cardForeground: "#E8ECF4",
    primary: "#3B62C4",
    primaryForeground: "#FFFFFF",
    secondary: "#0A1530",
    secondaryForeground: "#BDD0FF",
    muted: "#0A1530",
    mutedForeground: "#8A9BB5",
    accent: "#4B7BF5",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#132040",
    input: "#0A1530",
    success: "#22C55E",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    silver: "#607B9E",
    surface: "#0D1E3D",
  },
  radius: 12,
};

export default colors;
