export interface AppTheme {
  id: string;
  name: string;
  emoji: string;
  light: {
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    accent: string;
    accentForeground: string;
    success: string;
    muted: string;
    border: string;
    input: string;
    background: string;
    card: string;
  };
  dark: {
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    accent: string;
    accentForeground: string;
    success: string;
    muted: string;
    border: string;
    input: string;
    background: string;
    card: string;
  };
}

export const THEMES: AppTheme[] = [
  {
    id: 'casherk',
    name: 'كاشيرك الفيروزي',
    emoji: '🩵',
    light: {
      primary: '#0D9E96',
      primaryForeground: '#FFFFFF',
      secondary: '#E0FAF8',
      secondaryForeground: '#0D9E96',
      accent: '#1ABCB0',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#CCFAF7',
      border: '#A0EDE8',
      input: '#EDFCFB',
      background: '#F2FFFE',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#1ABCB0',
      primaryForeground: '#042F2E',
      secondary: '#0A2422',
      secondaryForeground: '#5DEAD4',
      accent: '#1ABCB0',
      accentForeground: '#042F2E',
      success: '#34D399',
      muted: '#0A2422',
      border: '#143533',
      input: '#0A2422',
      background: '#061A19',
      card: '#0D2523',
    },
  },
  {
    id: 'ocean',
    name: 'المحيط الأزرق',
    emoji: '🌊',
    light: {
      primary: '#1B3A7A',
      primaryForeground: '#FFFFFF',
      secondary: '#EAF0FB',
      secondaryForeground: '#1B3A7A',
      accent: '#435D91',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#E4EAF5',
      border: '#BCC5D8',
      input: '#E8EDF8',
      background: '#F4F6FA',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#7689AF',
      primaryForeground: '#0D1E3D',
      secondary: '#1C2D4A',
      secondaryForeground: '#BCC5D8',
      accent: '#435D91',
      accentForeground: '#FFFFFF',
      success: '#34D399',
      muted: '#1C2D4A',
      border: '#243656',
      input: '#1C2D4A',
      background: '#0D1E3D',
      card: '#1A2840',
    },
  },
  {
    id: 'forest',
    name: 'الغابة الخضراء',
    emoji: '🌲',
    light: {
      primary: '#166534',
      primaryForeground: '#FFFFFF',
      secondary: '#DCFCE7',
      secondaryForeground: '#166534',
      accent: '#22C55E',
      accentForeground: '#FFFFFF',
      success: '#15803D',
      muted: '#D1FAE5',
      border: '#A7F3D0',
      input: '#ECFDF5',
      background: '#F0FDF4',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#4ADE80',
      primaryForeground: '#052E16',
      secondary: '#122A1C',
      secondaryForeground: '#86EFAC',
      accent: '#4ADE80',
      accentForeground: '#052E16',
      success: '#4ADE80',
      muted: '#122A1C',
      border: '#1E3D27',
      input: '#122A1C',
      background: '#0C1F13',
      card: '#162A1E',
    },
  },
  {
    id: 'sunset',
    name: 'غروب الشمس',
    emoji: '🌅',
    light: {
      primary: '#C2410C',
      primaryForeground: '#FFFFFF',
      secondary: '#FFF7ED',
      secondaryForeground: '#C2410C',
      accent: '#F97316',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#FFEDD5',
      border: '#FED7AA',
      input: '#FFF7ED',
      background: '#FFFAF5',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#FB923C',
      primaryForeground: '#431407',
      secondary: '#2C1608',
      secondaryForeground: '#FDBA74',
      accent: '#FB923C',
      accentForeground: '#431407',
      success: '#34D399',
      muted: '#2C1608',
      border: '#3D2010',
      input: '#2C1608',
      background: '#1C0F05',
      card: '#271509',
    },
  },
  {
    id: 'rose',
    name: 'الوردي الدافئ',
    emoji: '🌹',
    light: {
      primary: '#BE123C',
      primaryForeground: '#FFFFFF',
      secondary: '#FFF1F2',
      secondaryForeground: '#BE123C',
      accent: '#E11D48',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#FFE4E6',
      border: '#FECDD3',
      input: '#FFF1F2',
      background: '#FFF5F5',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#FB7185',
      primaryForeground: '#4C0519',
      secondary: '#2D0A14',
      secondaryForeground: '#FDA4AF',
      accent: '#F43F5E',
      accentForeground: '#4C0519',
      success: '#34D399',
      muted: '#2D0A14',
      border: '#3D1020',
      input: '#2D0A14',
      background: '#1C0810',
      card: '#270C18',
    },
  },
  {
    id: 'purple',
    name: 'العنابي الملكي',
    emoji: '🍇',
    light: {
      primary: '#7C3AED',
      primaryForeground: '#FFFFFF',
      secondary: '#F5F3FF',
      secondaryForeground: '#7C3AED',
      accent: '#8B5CF6',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#EDE9FE',
      border: '#DDD6FE',
      input: '#F5F3FF',
      background: '#FAF8FF',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#A78BFA',
      primaryForeground: '#2E1065',
      secondary: '#1E1245',
      secondaryForeground: '#C4B5FD',
      accent: '#8B5CF6',
      accentForeground: '#2E1065',
      success: '#34D399',
      muted: '#1E1245',
      border: '#2A1860',
      input: '#1E1245',
      background: '#130E30',
      card: '#1C1540',
    },
  },
  {
    id: 'teal',
    name: 'الفيروزي البارد',
    emoji: '🌊',
    light: {
      primary: '#0F766E',
      primaryForeground: '#FFFFFF',
      secondary: '#F0FDFA',
      secondaryForeground: '#0F766E',
      accent: '#14B8A6',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#CCFBF1',
      border: '#99F6E4',
      input: '#F0FDFA',
      background: '#F5FFFE',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#2DD4BF',
      primaryForeground: '#042F2E',
      secondary: '#0D2928',
      secondaryForeground: '#5EEAD4',
      accent: '#14B8A6',
      accentForeground: '#042F2E',
      success: '#34D399',
      muted: '#0D2928',
      border: '#163836',
      input: '#0D2928',
      background: '#091C1B',
      card: '#122524',
    },
  },
  {
    id: 'golden',
    name: 'الذهبي الفاخر',
    emoji: '✨',
    light: {
      primary: '#92400E',
      primaryForeground: '#FFFFFF',
      secondary: '#FFFBEB',
      secondaryForeground: '#92400E',
      accent: '#D97706',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#FEF3C7',
      border: '#FDE68A',
      input: '#FFFBEB',
      background: '#FFFCF0',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#FBBF24',
      primaryForeground: '#451A03',
      secondary: '#261500',
      secondaryForeground: '#FCD34D',
      accent: '#F59E0B',
      accentForeground: '#451A03',
      success: '#34D399',
      muted: '#261500',
      border: '#352000',
      input: '#261500',
      background: '#1A1000',
      card: '#231600',
    },
  },
  {
    id: 'cherry',
    name: 'زهر الكرز',
    emoji: '🌸',
    light: {
      primary: '#9D174D',
      primaryForeground: '#FFFFFF',
      secondary: '#FDF2F8',
      secondaryForeground: '#9D174D',
      accent: '#EC4899',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#FCE7F3',
      border: '#FBCFE8',
      input: '#FDF2F8',
      background: '#FFF5FB',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#F472B6',
      primaryForeground: '#500724',
      secondary: '#2A0C18',
      secondaryForeground: '#F9A8D4',
      accent: '#EC4899',
      accentForeground: '#500724',
      success: '#34D399',
      muted: '#2A0C18',
      border: '#3A1224',
      input: '#2A0C18',
      background: '#1A0812',
      card: '#230D19',
    },
  },
  {
    id: 'midnight',
    name: 'منتصف الليل',
    emoji: '🌙',
    light: {
      primary: '#1E293B',
      primaryForeground: '#FFFFFF',
      secondary: '#F1F5F9',
      secondaryForeground: '#1E293B',
      accent: '#334155',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#E2E8F0',
      border: '#CBD5E1',
      input: '#F1F5F9',
      background: '#F8FAFC',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#94A3B8',
      primaryForeground: '#0F172A',
      secondary: '#1A2336',
      secondaryForeground: '#CBD5E1',
      accent: '#64748B',
      accentForeground: '#F8FAFC',
      success: '#34D399',
      muted: '#1A2336',
      border: '#232E42',
      input: '#1A2336',
      background: '#111825',
      card: '#192030',
    },
  },
  {
    id: 'indigo',
    name: 'النيلي العميق',
    emoji: '💙',
    light: {
      primary: '#3730A3',
      primaryForeground: '#FFFFFF',
      secondary: '#EEF2FF',
      secondaryForeground: '#3730A3',
      accent: '#4F46E5',
      accentForeground: '#FFFFFF',
      success: '#16A34A',
      muted: '#E0E7FF',
      border: '#C7D2FE',
      input: '#EEF2FF',
      background: '#F5F7FF',
      card: '#FFFFFF',
    },
    dark: {
      primary: '#818CF8',
      primaryForeground: '#1E1B4B',
      secondary: '#181633',
      secondaryForeground: '#A5B4FC',
      accent: '#6366F1',
      accentForeground: '#1E1B4B',
      success: '#34D399',
      muted: '#181633',
      border: '#221E44',
      input: '#181633',
      background: '#100F28',
      card: '#181636',
    },
  },
];

export const DEFAULT_THEME_ID = 'casherk';

export function getThemeById(id: string): AppTheme {
  return THEMES.find((t) => t.id === id) ?? THEMES[0];
}
