kind = "mobile"
previewPath = "/"
title = "كاشيرك - إدارة المخزون"
version = "1.0.0"
id = "artifacts/mujahid"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24425

[services.development]
run = "pnpm --filter @workspace/casherk run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/casherk", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/casherk", "run", "serve" ]

[services.env]
PORT = "24425"
BASE_PATH = "/"
